module.exports = {
  walletAddress: '0x9BeD7776262076B016798d6Ee74Dea3a6B1Ac662',
  kiteRpc: 'https://rpc.gokite.ai/',
  port: process.env.PORT || 3000,
  services: {
    audit:           { price: '2.00', description: 'Smart contract security audit' },
    whitepaper:      { price: '0.50', description: 'Crypto whitepaper summarizer' },
    transaction:     { price: '0.20', description: 'Blockchain transaction explainer' },
    token_sentiment: { price: '0.30', description: 'Token sentiment analyzer' },
    trading_signal:  { price: '1.00', description: 'Trading signal analyzer' },
    pitch:           { price: '1.50', description: 'Startup pitch deck reviewer' },
    business:        { price: '1.00', description: 'Business plan analyzer' },
    contract:        { price: '0.75', description: 'Legal contract summarizer' },
    competitors:     { price: '1.00', description: 'Competitor analysis' },
    job:             { price: '0.50', description: 'Job description writer' },
    blog:            { price: '0.50', description: 'Blog post generator' },
    linkedin:        { price: '0.30', description: 'LinkedIn post writer' },
    email:           { price: '0.25', description: 'Cold email writer' },
    product:         { price: '0.25', description: 'Product description writer' },
    resume:          { price: '0.75', description: 'Resume reviewer' },
    debug:           { price: '0.50', description: 'Code debugger' },
    explain_code:    { price: '0.30', description: 'Code explainer' },
    sql:             { price: '0.25', description: 'SQL query generator' },
    api_docs:        { price: '0.75', description: 'API documentation writer' },
    tests:           { price: '0.50', description: 'Unit test generator' },
    summarize:       { price: '0.10', description: 'Text summarizer' },
    research:        { price: '0.50', description: 'Research paper breakdown' },
    data:            { price: '0.40', description: 'Data interpreter' },
    news:            { price: '0.25', description: 'News sentiment analyzer' },
    sentiment:       { price: '0.05', description: 'Sentiment analyzer' },
    advice:          { price: '0.20', description: 'AI advice' }
  }
}
